version: "3.6"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wolframabsolute
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - /home/Docker/Volumes/Mysql/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  app:
    image: new-spring-boot-app:latest
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wolframabsolute
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - mysql
  app-ui:
    image: new-angular-front-end:latest
    build: ./front-end
    ports:
      - 4200:4200
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
