/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeConverter */

#ifndef _Included_NativeConverter
#define _Included_NativeConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeConverter
 * Method:    convert
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeConverter_convert
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
